admin/routes.py
from functools import wraps
from flask import Blueprint, flash, jsonify, redirect, render_template, request, session, url_for
from conn import CRUDFunction
from connection.controller import connection
import pyodbc
import base64

admin = Blueprint('admin', __name__, url_prefix='/admin', template_folder='templates', static_folder='static')
sess = {
    'admin_logged_in': False,
    'admin_usertype': ''
}

@admin.before_request
def make_session_permanent():
	session.permanent = True

def user_role_admin(f):
	@wraps(f)
	def wrap(*args, **kwargs):
		if session['admin_logged_in'] == True:           
			if session['admin_usertype'] == 'admin':
				return f(*args, **kwargs)
			else:
				flash('You do not have privilege to access this page!','danger')
				return redirect(url_for('index.main'))
		else:
			flash('Unauthorized, Please login!','danger')
			return redirect(url_for('index.main'))
	return wrap

@admin.route('/', methods=['GET', 'POST'])
def index():
    session['admin_logged_in'] = False
    session['admin_usertype'] = ''
    if request.method == 'POST':
        try:
            admin_username = request.form.get('username')
            admin_password = request.form.get('password')

            conn = connection()
            cur = conn.cursor()
            proc = 'Exec spReadAdmins @admin_username=?, @admin_password=?, @statement_type=?'
            param = admin_username, admin_password, "SELECT"
            cur.execute(proc, param)
            rows = cur.fetchone()
            cur.close()
            conn.commit()
            if rows:
                session['admin_logged_in'] = True
                session['admin_usertype'] = 'admin'
                sess['admin_logged_in'] = True
                sess['admin_usertype'] = 'admin'
                return redirect(url_for('admin.dashboard'))
            else:
                return render_template('admin_login.html')
        except (pyodbc.Error) as e:
            message = e
            return render_template('admin_login.html', message=message)
    return render_template('admin_login.html')

@admin.route('/dashboard',  methods=['GET','POST'])
def dashboard():
    if sess['admin_logged_in'] == True and sess['admin_usertype'] == 'admin':
        return render_template('admin_dashboard.html')
    return redirect(url_for('index.main'))

@admin.route('/add-faculty', methods=['GET','POST'])
def add_faculty():
    if sess['admin_logged_in'] == True and sess['admin_usertype'] == 'admin':
        if request.method=='POST':
            try:
                faculty_name=request.form.get("faculty_name")
                faculty_code=request.form.get("faculty_code")
                faculty_description=request.form.get("faculty_description")
                con=connection()
                cur=con.cursor()
                stored_proc="Exec spCRUDFaculty @faculty_id=?, @faculty_name=?, @faculty_code=?,@faculty_Description=?,@StatementType=?"
                param="1",faculty_name, faculty_code, faculty_description, "INSERT"
                cur.execute(stored_proc, param)
                cur.close()
                con.commit()
                flash("Registration successful.")
                session['admin_logged_in'] = True
                session['admin_usertype'] = 'admin'
                return redirect(url_for('admin.dashboard'))
            except (pyodbc.Error) as e:
                message=e
                return render_template('add_faculty.html', message=message)
        return render_template('add_faculty.html')
    return redirect(url_for('index.main'))

@admin.route('/add-department', methods=['GET', 'POST'])
def add_department():
    if sess['admin_logged_in'] == True and sess['admin_usertype'] == 'admin':
        if request.method == 'POST':
            try:
                dept_name = request.form.get('department_name')
                dept_code = request.form.get('department_code')
                dept_description = request.form.get('department_description')
                faculty_id = request.form.get('faculty_id')

                conn = connection()
                cur = conn.cursor()
                stored_proc = 'EXEC spCRUDDepartment @department_id=?, @department_name=?, @department_code=?, @department_description=?, @faculty_id=?, @StatementType=?'
                param = '1', dept_name, dept_code, dept_description, faculty_id, "INSERT"
                cur.execute(stored_proc, param)
                cur.close()
                conn.commit()
                session['admin_logged_in'] = True
                session['admin_usertype'] = 'admin'
                return redirect(url_for('admin.dashboard'))
            except (pyodbc.Error) as e:
                message = e
                return render_template('add_department.html', message=message)
        conn = connection()
        cur = conn.cursor()
        stored_proc = 'Exec spCRUDFaculty @faculty_id=?, @faculty_code=?, @faculty_name=?, @faculty_description=?, @StatementType=?'
        param = "1",'','','',"SELECT" #to allow the procedure to run without issues
        cur.execute(stored_proc, param)
        rows = cur.fetchall()
        cur.close()
        conn.commit()
        return render_template('add_department.html', rows = rows)
    return redirect(url_for('index.main'))

@admin.route('/add-student', methods=['GET', 'POST'])
def add_student():
    if sess['admin_logged_in'] == True and sess['admin_usertype'] == 'admin':
        if request.method == 'POST':
            try:
                student_name = request.form.get('student_name')
                matric_num = request.form.get('matric_num')
                tel_num = request.form.get('tel_num')
                email = request.form.get('email')
                dept_id = request.form.get('department_id')
                student_image_data = request.form.get('student_image')
                level = request.form.get('level_id')
                print('Message still working fine')
                conn = connection()
                cur = conn.cursor()
                print('Message, Connection Successful')
                stored_proc = 'Exec spCRUDStudent @student_id=?, @student_name=?, @matric_num=?, @tel_num=?, @email=?, @department_id=?, @student_image=?, @level_id=?, @StatementType=?'
                param = '1', student_name, matric_num, tel_num, email, dept_id, student_image_data, level, "INSERT"
                cur.execute(stored_proc, param)
                print('This also completed successfully')
                cur.close()
                conn.commit()
                session['admin_logged_in'] = True
                session['admin_usertype'] = 'admin'
                print("This session statement is after the function to add students", session)
                return redirect(url_for('admin.dashboard'))
            except (pyodbc.Error) as e:
                message = e
                return render_template('add_student.html', message=message)
        return render_template('add_student.html')
    return redirect(url_for('index.main'))

@admin.route('/add-staff', methods=['GET', 'POST'])
def add_staff():
    if sess['admin_logged_in'] == True and sess['admin_usertype'] == 'admin':
        if request.method == 'POST':
            try:
                staff_name = request.form.get('staff_name')
                staff_reg_num = request.form.get('staff_reg_num')
                tel_num = request.form.get('tel_num')
                email = request.form.get('email')
                dept_id = request.form.get('department_id')
                staff_image_data = request.form.get('staff_image')
                print('Message, still working fine`')
                conn = connection()
                cur = conn.cursor()
                stored_proc = 'Exec spCRUDStaff @staff_id=?, @staff_name=?, @staff_reg_number=?, @tel_num=?, @email=?, @department_id=?, @staff_image=?, @StatementType=?'
                param = '1', staff_name, staff_reg_num, tel_num, email, dept_id, staff_image_data, "INSERT"
                cur.execute(stored_proc, param)
                cur.close()
                conn.commit()
                session['admin_logged_in'] = True
                session['admin_usertype'] = 'admin'
                return redirect(url_for('admin.dashboard'))
            except (pyodbc.Error) as e:
                message = e
                return render_template('add_staff.html', message=message)
        return render_template('add_staff.html')
    return redirect(url_for('index.main'))

@admin.route('/add-level', methods=['GET', 'POST'])
def add_level():
    if sess['admin_logged_in'] == True and sess['admin_usertype'] == 'admin':
        if request.method == 'POST':
            try:
                level = request.form.get('level_name')
                conn = connection()
                cur = conn.cursor()
                stored_proc = 'Exec spCRUDLevel @level_id=?, @level_name=?, @StatementType=?'
                param = '1', level, 'INSERT'
                cur.execute(stored_proc, param)
                cur.close()
                conn.commit()
                session['admin_logged_in'] = True
                session['admin_usertype'] = 'admin'
                return redirect(url_for('admin.dashboard'))
            except (pyodbc.Error) as e:
                message = e
                return render_template('add_level.html', message=message)
        return render_template('add_level.html')
    return redirect(url_for('index.main'))

@admin.route('/add-sessions', methods=['GET', 'POST'])
def add_session():
    if sess['admin_logged_in'] == True and sess['admin_usertype'] == 'admin':
        if request.method == 'POST':
            try:
                session_start = request.form.get('session_start')
                session_end = request.form.get('session_end')

                conn = connection()
                cur = conn.cursor()

admin/templates/add_classes.html
{% extends 'adding_form_template.html' %}

{% block content %}
    <div class="generic-head-form-container">
        <div class="generic-main-form--container">
            <div class="generic-main-form-container-text">
                <h1>Add New Classes Here</h1>
            </div>
            <form action="{{url_for('admin.add_classes')}}" method="post" id="addClasses" class="generic-form">
                <input type="date" name="class_date" id="class_date" required placeholder="Class Date">
                <input type="time" name="class_start" id="class_start" required placeholder="Class Start Time">
                <input type="time" name="class_end" id="class_end" required placeholder="Class End Time">
                <input type="text" name="course_id" id="course_id" required placeholder="Course Id">
                <button type="submit">Submit</button>
            </form>
        </div>
    </div>

{% endblock %}

admin/templates/add_courses.html
{% extends 'adding_form_template.html' %}

{% block content %}
    <div class="generic-head-form-container">
        <div class="generic-main-form--container">
            <div class="generic-main-form-container-text">
                <h1>Add New Courses Here</h1>
            </div>
            <form action="{{url_for('admin.add_courses')}}" method="post", id="addCourses" class="generic-form">
                <input type="text" name="course_name" id="course_name" required placeholder="Course Name">
                <input type="text" name="course_code" id="course_code" required placeholder="Course Code">
                <input type="text" name="department_id" id="department_id" required placeholder="Department Id">
                <input type="text" name="level_id" id="level_id" required placeholder="Level Id">
                <input type="text" name="semester_id" id="semester_id" required placeholder="Semester Id">
                <input type="text" name="staff_id" id="staff_id" required placeholder="Staff Id">
                <button type="submit">submit</button>
            </form>
        </div>
    </div>
{% endblock %}

admin/templates/add_department.html
{% extends 'adding_form_template.html' %}

{% block content %}
    <div class="generic-head-form-container">
        <div class="generic-main-form--container">
            <div class="generic-main-form-container-text">
                <h1>Add New Departments Here</h1>
            </div>
            <form action="{{url_for('admin.add_department')}}" method="post" id="addDepartment" class="generic-form">
                <input type="text" name="department_name" id="department_name" required placeholder="Department Name">
                <input type="text" name="department_code" id="department_code" required placeholder="Department Code">
                <input type="text" name="department_description" id="department_description" required placeholder="Department Description">
                <input type="text" name="faculty_id" id="faculty_id" required placeholder="Faculty id">
        
                <button type="submit">Submit</button>
            </form>
        </div>
    </div>

    <!-- {% for row in rows %}
        <div class="faculty-block">
            <span>{{row.faculty_id}}</span>
            <span>{{row.faculty_name}}</span>
            <span>{{row.faculty_code}}</span>
        </div>
    {% endfor %} -->

{% endblock %}

admin/templates/add_faculty.html
{% extends 'adding_form_template.html' %}

{% block content %}
    <div class="faculty-to-center">
        <div class="faculty-head-form-container">
            <div class="faculty-main-form--container">
                <div class="faculty-main-form-container-text">
                    <h1>Register A New Faculty Here</h1>
                </div>
                <form id="frmAddFaculty" method="post" action="{{url_for('admin.add_faculty')}}" class="add-faculty-form">
                    <input type="text" id="faculty_name" name="faculty_name" required placeholder="Enter Faculty Name">
                    <input type="text" id="faculty_name" name="faculty_code" required placeholder="Enter Faculty Code">
                    <input type="text" id="faculty_name" name="faculty_description" required placeholder="Enter Faculty Description">
                    <button type="submit">submit</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

admin/templates/add_level.html
{% extends 'adding_form_template.html' %}

{% block content %}
    <div class="generic-head-form-container">
        <div class="generic-main-form--container">
            <div class="generic-main-form-container-text">
                <h1>Add Levels Here</h1>
            </div>
            <form action="{{url_for('admin.add_level')}}" method="post" id="addLevel" class="generic-form">
                <p><input type="text" required name="level_name" id="level_name" placeholder="Level"></p>
                <button type="submit">Submit</button>
            </form>
        </div>
    </div>

{% endblock %}

admin/templates/add_programme.html
{% extends 'adding_form_template.html' %}

{% block content %}
    <div class="generic-head-form-container">
        <div class="generic-main-form--container">
            <div class="generic-main-form-container-text">
                <h1>Add New Programmes Here</h1>
            </div>
            <form action="{{url_for('admin.add_programme')}}" method="post" id="addProgramme" class="generic-form">
                <input type="text" name="programme_name" id="programme_name" required placeholder="Programme Name">
                <input type="text" name="programme_duration" id="programme_durations" required placeholder="Programme Duration (in years)">
                <input type="text" name="department_id" id="department_id" required placeholder="Department Id">
                <button type="submit">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

admin/templates/add_semester.html
{% extends 'adding_form_template.html' %}

{% block content %}
    <div class="generic-head-form-container">
        <div class="generic-main-form--container">
            <div class="generic-main-form-container-text">
                <h1>Add New Semesters Here</h1>
            </div>
            <form action="{{url_for('admin.add_semester')}}" method="post" id="addSemester" class="generic-form">
                <input type="date" name="semester_start" id="semester_start" required placeholder="Semester Start">
                <input type="date" name="semester_end" id="semester_end" required placeholder="Semester End">
                <input type="text" name="session_id" id="session_id" required placeholder="Session Id">
                <button type="submit">Submit</button>
                {{message}}
            </form>
        </div>
    </div>

{% endblock %}

admin/templates/add_session.html
{% extends 'adding_form_template.html' %}

{% block content %}
    <div class="generic-head-form-container">
        <div class="generic-main-form--container">
            <div class="generic-main-form-container-text">
                <h1>Add New Sessions Here</h1>
            </div>
            <form action="{{url_for('admin.add_session')}}" method="post" id="addSession" class="generic-form">
                <input type="date" name="session_start" id="session_start" required placeholder="Session Start">
                <input type="date" name="session_end" id="session_end" required placeholder="Session End">
                <button type="submit">Submit</button>
                {{message}}
            </form>
        </div>
    </div>

{% endblock %}

admin/templates/add_staff.html
{% extends 'adding_form_template.html' %}

{% block content %}
    <div class="student-head-form-container">
        <div class="student-main-form-container">
            <div class="student-main-form-container-text">
                <h1>Register Staffs Here</h1>
            </div>
            <form action="{{url_for('admin.add_staff')}}" method="post" id="addStaff" class="add-student-form">
                <input type="text" name="staff_name" id="staff_name" required placeholder="Staff Name">
                <input type="text" name="staff_reg_num" id="staff_reg_num" required placeholder="Staff Registration Number">
                <input type="tel" name="tel_num" id="tel_num" required placeholder="Phone Number">
                <input type="email" name="email" id="email" required placeholder="Email">
                <input type="text" name="department_id" id="department_id" required placeholder="Department Id">
                <input type="hidden" name="staff_image" id="staff_image">
                <div class="video-image-holder" id="video-image-holder">
                    <video id="video" width="340" height="340" autoplay></video>
                    <button id="capture-btn" type="button">Capture</button>
                    <canvas id="canvas" width="640" height="480" style="display: none;"></canvas>
                </div>
                <button type="submit" id="submit-btn">Submit</button>
                <script src="{{url_for('admin.static', filename='js/staff.js')}}"></script>
            </form>
        </div>
    </div>
{% endblock %}

admin/templates/add_student.html
{% extends 'adding_form_template.html' %}

{% block content  %}
    <div class="student-head-form-container">
        <div class="student-main-form-container">
            <div class="student-main-form-container-text">
                <h1>Register Students Here</h1>
            </div>
            <form action="{{url_for('admin.add_student')}}" method="post" id="addStudent" class="add-student-form">
                <input type="text" name="student_name" id="student_name" required placeholder="Student Name">
                <input type="text" name="matric_num" id="matric_num" required placeholder="Matric Number">
                <input type="tel" name="tel_num" id="tel_num" required placeholder="Phone Number">
                <input type="email" name="email" id="email" required placeholder="Email">
                <input type="text" name="department_id" id="department_id" required placeholder="Department Id">
                <input type="text" name="level_id" id="level_id" required placeholder="Level">
                <input type="hidden" name="student_image" id="student_image">
                <div class="video-image-holder" id="video-image-holder">
                    <video id="video" width="340" height="340" autoplay></video>
                    <button id="capture-btn" type="button">Capture</button>
                    <canvas id="canvas" width="340" height="340" style="display: none;"></canvas>
                </div>
                <button type="submit" id="submit-btn">Submit</button>
                <script src="{{url_for('admin.static', filename='js/student.js')}}"></script>
            </form>
        </div>
    </div>
{% endblock %}

admin/templates/admin_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{{url_for('admin.static', filename='css/admin_dashboard.css')}}">
</head>
<body>
    <div class="content-holder">
        <h1>This is the admin section of this application</h1>
        <div class="content-link-holder">
            <a href="{{url_for('admin.manage_faculty')}}"><div class="content-holder-card">
                <p>Faculty</p>
            </div></a>
            <a href="{{url_for('admin.manage_department')}}"><div class="content-holder-card">
                <p>Department</p>
            </div></a>
            <a href="{{url_for('admin.manage_programme')}}"><div class="content-holder-card">
                <p>Programme</p>
            </div></a>
            <a href="{{url_for('admin.manage_level')}}"><div class="content-holder-card">
                <p>Level</p> 
            </div></a>
            <a href="{{url_for('admin.manage_session')}}"><div class="content-holder-card">
                <p>Session</p>
            </div></a>
            <a href="{{url_for('admin.manage_semester')}}"><div class="content-holder-card">
                <p>Semester</p>
            </div></a>
            <a href="{{url_for('admin.manage_courses')}}"><div class="content-holder-card">
                <p>Courses</p>
            </div></a>
            <a href="{{url_for('admin.manage_classes')}}"><div class="content-holder-card">
                <p>Classes</p>
            </div></a>
            <a href="{{url_for('admin.add_student')}}"><div class="content-holder-card">
                <p>Add New Student</p>
            </div></a>
            <a href="{{url_for('admin.add_staff')}}"><div class="content-holder-card">
                <p>Add New Staff</p>
            </div></a>
        </div>
    </div>
</body>
</html>

admin/templates/manage_courses.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{{url_for('admin.static', filename='css/manage_faculty.css')}}">
</head>
<body>
    <div class="add-button-holder">
        <a href="{{url_for('admin.add_courses')}}"><button>Add Courses</button></a>
    </div>
    {% for row in rows %}
        <div class="faculty-rows">
            <div class="faculty-rows-faculty-details">
                <span>{{row.course_id}}</span>
                <span>{{row.course_code}}</span>   
                <span>{{row.course_name}}</span>
            </div>
            <div class="faculty-rows-buttons">
                <button class="update-button">Update</button>
                <button class="delete-button">Delete</button>
            </div>
        </div>
    {% endfor %}
</body>
</html>

admin/templates/manage_level.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{{url_for('admin.static', filename='css/manage_faculty.css')}}">
</head>
<body>
    <div class="add-button-holder">
        <a href="{{url_for('admin.add_level')}}"><button>Add Level</button></a>
    </div>
    {% for row in rows %}
        <div class="faculty-rows">
            <div class="faculty-rows-faculty-details">
                <span>{{row.level_id}}</span>  
                <span>{{row.level_name}}</span>
            </div>
            <div class="faculty-rows-buttons">
                <button class="update-button">Update</button>
                <button class="delete-button">Delete</button>
            </div>
        </div>
    {% endfor %}
</body>
</html>

admin/templates/manage_programme.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{{url_for('admin.static', filename='css/manage_faculty.css')}}">
</head>
<body>
    <div class="add-button-holder">
        <a href="{{url_for('admin.add_programme')}}"><button>Add Programme</button></a>
    </div>
    {% for row in rows %}
        <div class="faculty-rows">
            <div class="faculty-rows-faculty-details">
                <span>{{row.programme_id}}</span>
                <span>{{row.programme_duration}} (Years)</span>   
                <span>{{row.programme_name}}</span>
            </div>
            <div class="faculty-rows-buttons">
                <button class="update-button">Update</button>
                <button class="delete-button">Delete</button>
            </div>
        </div>
    {% endfor %}
</body>
</html>