instructor/routes.py
import base64
from functools import wraps
import cv2
from flask import Blueprint, flash, jsonify, render_template, request, redirect, session, url_for
from connection.controller import connection
import pyodbc
import numpy as np
from deepface import DeepFace


instructor = Blueprint('instructor', __name__, url_prefix='/instructor', template_folder='templates', static_folder='static')
sess = {
    'instructor_logged_in': False,
    'instructor_usertype': 'instructor'
}

@instructor.before_request
def make_session_permanent():
	session.permanent = True

def user_role_instructor(f):
	@wraps(f)
	def wrap(*args, **kwargs):
		if session['instructor_logged_in'] == True:           
			if session['instructor_usertype'] == 'instructor':
				return f(*args, **kwargs)
			else:
				flash('You do not have privilege to access this page!','danger')
				return redirect('index.main')
		else:
			flash('Unauthorized, Please login!','danger')
			return redirect(url_for('instructor.instructor_login'))
	return wrap

@instructor.route('/', methods=['GET', 'POST'])
def instructor_login():
    session['instructor_logged_in'] = False
    session['instructor_usertype'] = ''
    if request.method == 'POST':
        try:
            staff_reg_number = request.form.get('staff_reg_num')
            password = request.form.get('password')
            staff_image_data = request.form.get('staff_image')
            conn = connection()
            cur = conn.cursor()
            stored_proc = 'Exec spAuthStaff @staff_reg_number=?, @staff_password=?'
            param = staff_reg_number, password
            cur.execute(stored_proc, param)
            rows = cur.fetchone()
            cur.close()
            conn.commit()
            if rows:
                staff_db_image = rows.staff_image
                nparr1 = np.frombuffer(base64.b64decode(staff_image_data), np.uint8)
                nparr2 = np.frombuffer(base64.b64decode(staff_db_image), np.uint8)
                img1 = cv2.imdecode(nparr1, cv2.COLOR_BGR2GRAY)
                img2 = cv2.imdecode(nparr2, cv2.COLOR_BGR2GRAY)
                img_result = DeepFace.verify(img1, img2, enforce_detection=False)
                print(img_result)
                if img_result['verified'] == True:
                    sess['instructor_logged_in'] = True
                    sess['instructor_usertype'] = 'instructor'
                    session['instructor_logged_in'] = True
                    session['instructor_usertype'] = 'instructor'
                    sess['staff_id'] = rows.staff_id
                    session['staff_id'] = rows.staff_id
                    return redirect(url_for('instructor.landing'))
                else:
                    error = 'Either Image not Verified or  Your Details Are Invalid'
                    return render_template('instructor_login.html', error=error)
            else:
                error = 'Email not found. Are you sure you\'re registered?'
                return render_template('instructor_login.html', error=error)
        except (pyodbc.Error) as e:
            message = e
            return render_template('instructor_login.html', message=message)
    return render_template('instructor_login.html')

@instructor.route('/landing', methods=['GET', 'POST'])
def landing():
    if sess['instructor_logged_in'] == True and sess['instructor_usertype'] == 'instructor':
        return render_template('instructor_landing.html')
    return redirect(url_for('index.main'))

@instructor.route('/classes', methods=['GET', 'POST'])
def view_classes():
    if sess['instructor_logged_in'] == True and sess['instructor_usertype'] == 'instructor':
        staff_id = sess['staff_id']
        conn = connection()
        cur = conn.cursor()
        stored_proc = 'Exec getClassDetails @staff_id=?'
        param = staff_id
        cur.execute(stored_proc, param)
        rows = cur.fetchall()
        cur.close()
        conn.close()
        return render_template('assigned_classes.html', rows=rows)
    return redirect(url_for('index.main'))

@instructor.route('/attend-class', methods=['GET', 'POST'])
def attend_classes():
    if sess['instructor_logged_in'] == True and sess['instructor_usertype'] == 'instructor':
        staff_id = sess['staff_id']
        conn = connection()
        cur = conn.cursor()
        stored_proc = 'Exec getStaffClasses @staff_id=?'
        param = staff_id
        cur.execute(stored_proc, param)
        rows = cur.fetchall()
        cur.close()
        conn.close()
        return render_template('attend_class.html', rows=rows)
    return redirect(url_for('index.main'))

@instructor.route('/go-meet', methods=['GET', 'POST'])
def go_meet():
    class_id = request.form.get('class_id')
    meet_id = request.form.get('meetid')
    sess['class_id'] = class_id
    sess['meet_id'] = meet_id
    return redirect(url_for('video.meeting', uid=meet_id))

@instructor.route('/take-attendance', methods=['GET', 'POST'])
def take_attendance():
    if request.method == 'POST':
        staff_id = sess['staff_id']
        class_id = sess['class_id']
        conn = connection()
        cur = conn.cursor()
        stored_proc = 'Exec spCRUDStaff_Attendance @staff_attendance_id=?, @staff_id=?, @class_id=?, @StatementType=?'
        param = '1', staff_id, class_id, 'INSERT'
        cur.execute(stored_proc, param)
        cur.close()
        conn.commit()
        return jsonify({'message':'success'})
    return render_template('attend_class.html')


@instructor.route('/logout')
def logout():
      session.clear()
      return redirect(url_for('instructor.instructor_login'))

instructor/templates/assigned_classes.html
{% extends 'instructor_index.html' %}

{% block title %}Assigned Classes{% endblock %}

{% block content %}
    {% if rows %}
        <div class="assigned-classes-holder">
            <div class="assigned-classes-content">
                <h1>These are the Courses You've Been Assigned</h1>
                {% for row in rows %}
                    <div class="assigned-courses-div">
                        <div class="assigned-course-detail">
                            <span class="code">{{row.course_code}}</span>
                            <span>{{row.course_name}}</span>
                        </div>
                        <div class="number-of-students">
                            <span>{{row.Number_Of_Students}}</span>
                        </div>
                    </div>
                {% endfor %}
            </div> 
        </div>
    {% else %}
        <div class="text-if-nothing">
            <h1>There are no Assigned Courses For Now</h1>
        </div>
    {% endif %}
{% endblock %}

instructor/templates/attend_class.html
{% extends 'instructor_index.html' %}

{% block title %}Attend Class{% endblock %}

{% block content %}
    <div class="attend-classes-holder">
        <div class="attend-classes-content">
            <h1>Your Classes</h1>
            <div class="attend-classes-cards-holder">
                {% for row in rows %}
                    <form action="#" method="post">
                        <input type="hidden" name="class_id" id="class_id" value="{{row.class_id}}">
                        <input type="hidden" name="meetid" id="meetid" value="{{row.meet_id}}">
                        <div class="attend-classes-cards">
                            <div class="attend-classes-heading">
                                <p class="code">{{row.course_code}}</p>
                                <p class="name">{{row.course_name}}</p>
                            </div>
                            <div class="class-date">
                                <p>{{row.class_date}}</p>
                            </div>
                            <div class="class-timing">
                                <span>{{row.class_in}}</span>
                                <span>To</span>
                                <span>{{row.class_out}}</span>
                            </div>
                            <div class="attend-class-button">
                                <button type="submit">Attend Class</button>
                            </div>
                        </div>
                    </form>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

instructor/templates/instructor_index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{{url_for('instructor.static', filename='css/instructor_index.css')}}">
</head>
<body>
    {% block content %}

    {% endblock %}
</body>
</html>

instructor/templates/instructor_landing.html
{% extends 'instructor_index.html' %}

{% block title %}Landing Page{% endblock %}

{% block content %}
    <div class="landing-box">
        <div class="major-container">
            <h1>Instructor Landing Page</h1>
            <div class="container-link-holder">
                <a href="{{url_for('instructor.view_classes')}}">
                    <div class="container-link-card">
                        <span>View Classes</span>
                    </div>
                </a>
                <a href="{{url_for('instructor.attend_classes')}}">
                    <div class="container-link-card">
                        <span>Attend Classes</span>
                    </div>
                </a>
                <a href="{{url_for('instructor.logout')}}">
                    <div class="container-link-card">
                        <span>Logout</span>
                    </div>
                </a>
            </div>
        </div>
    </div>
{% endblock %}

instructor/templates/instructor_login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{{url_for('instructor.static', filename='css/instructor_login.css')}}">
</head>
<body>
    <div class="full-screen-body">
        <div class="instructor-login-transbox">
            <div class="instructor-login-form-holder">
                <div class="instructor-login-form">
                    <h1>Staff Login</h1>
                    <form action="{{url_for('instructor.instructor_login')}}" method="post">
                        <span>Staff Registration Number</span>
                        <p><input type="text" name="staff_reg_num" id="staff_reg_num" required placeholder="Staff Registration Number"></p>
                        <span>Password</span>
                        <p><input type="password" name="password" id="password" required placeholder="Password"></p>
                        <video id="video" width="180" height="200" autoplay></video>
                        <div class="capturedImageHolder" id="capturedImageHolder" style="display: none;"></div>
                        <input type="hidden" name="staff_image" id="staff_image">
                        <button id="capture-btn" type="button">Capture Image</button>
                        <canvas id="canvas" width="180" height="200" style="display: none;"></canvas>
                        <button type="submit">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <script src="{{url_for('instructor.static', filename='js/staffAuth.js')}}"></script>
</body>
</html>